# Generated by Django 5.1.3 on 2024-11-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='error_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
