# Generated by Django 5.1.3 on 2024-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_topicscore_classification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='training_examples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='validation_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='parameters',
            field=models.JSONField(default={'batch_size': 16, 'model_type': 'medium', 'num_epochs': 2, 'num_iterations': 20}),
        ),
    ]
