# Generated by Django 5.1.3 on 2024-11-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_modelconfig_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='model_config',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='model_metrics',
        ),
        migrations.AlterField(
            model_name='topic',
            name='templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
