# Generated by Django 5.1.3 on 2024-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_topic_model_config_remove_topic_model_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
