# Generated by Django 5.1.4 on 2025-02-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_modelconfig_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='slug',
            field=models.SlugField(blank=True, help_text='must be unique', unique=True),
        ),
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, help_text='must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='path',
            field=models.CharField(blank=True, help_text='path for traversal', max_length=1000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, help_text='must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='templates',
            field=models.JSONField(blank=True, default=dict, help_text='templates for content generation'),
        ),
    ]
